# adapted from
# https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/lib/gitlab/ci/templates/C%2B%2B.gitlab-ci.yml
#
# To help test config (e.g. library versions and files)
# - docker pull gcc
# - docker images
# - docker run -it #####
#
image: gcc

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build_and_test:

  stage: build
  before_script:
    - apt update && apt install -y libcgal-dev
    #- apt update && apt -y install cmake libgsl-dev
    - ls -l /usr/include/CGAL/Exact_predicates_inexact_constructions_kernel.h
  script:
    # this line sets up autotools pieces in both FJ and SISCone
    - NOCONFIGURE=true ./autogen.sh
    # and runs configure with the given flags
    - ./configure --enable-allcxxplugins --enable-cgal
    - make -j4
    - make check
