# common fastjet definitions
include ../../makefile.static

CXXSRC = NestedAlgsPlugin.cc 
OBJS = $(patsubst %.cc,%.o,$(CXXSRC)) 

# fastjet includes
FASTJET_INCLUDE = -I../../include
INCLUDE += $(FASTJET_INCLUDE)

all: libNestedAlgsPlugin.a

libNestedAlgsPlugin.a: $(OBJS)
	ar cru libNestedAlgsPlugin.a $(OBJS)
	ranlib libNestedAlgsPlugin.a

clean:
	rm -f $(OBJS)

distclean: clean
	rm -f libNestedAlgsPlugin.a *~

# NB: only use "relative" includes here (others are too subject
#     to change according to the system one is on...)
depend:
	makedepend  -f makefile.static $(FASTJET_INCLUDE) -I. -I./fastjet --   -- $(CXXSRC)

# DO NOT DELETE

NestedAlgsPlugin.o: ../../include/fastjet/ClusterSequence.hh
NestedAlgsPlugin.o: ../../include/fastjet/internal/DynamicNearestNeighbours.hh
NestedAlgsPlugin.o: ../../include/fastjet/internal/numconsts.hh
NestedAlgsPlugin.o: ../../include/fastjet/internal/base.hh
NestedAlgsPlugin.o: ../../include/fastjet/PseudoJet.hh
NestedAlgsPlugin.o: ../../include/fastjet/Error.hh
NestedAlgsPlugin.o: ../../include/fastjet/JetDefinition.hh
NestedAlgsPlugin.o: fastjet/NestedAlgsPlugin.hh
