EXTRA_DIST = ghost-extent-y3.pdf ghost-extent-y3.eps ghost-extent-y4.eps ghost-extent-y4.pdf timings_best_3_0_1.eps \
     fj31-best-strategy-manual-akt.eps \
     fj31-best-strategy-manual-akt.pdf \
     fj31-best-strategy-manual-cam.eps \
     fj31-best-strategy-manual-cam.pdf \
     fj31-best-strategy-manual-kt.eps  \
     fj31-best-strategy-manual-kt.pdf  \
     fj31_timings_best_R0.4.eps	       \
     fj31_timings_best_R0.4.pdf	       \
     fj31_timings_best_R1.2.eps	       \
     fj31_timings_best_R1.2.pdf        

