# generated by running 
# ./area-border-fractal-dimension -antikt -ghost_area $a 
# with many ghost areas
# format: area (requested, not actual...) av.jet.border-length error
0.2 5.1746 +- 0.330665
0.1 8.95161 +- 0.569091
0.05 14.8182 +- 0.93816
0.025 19.8 +- 1.473
0.0125 30.9867 +- 2.16279
0.00625 44.4074 +- 3.21017
0.003125 64.4337 +- 4.55212
0.0015 90.7011 +- 6.3599
0.00075 135.131 +- 9.74295
0.000375 211.313 +- 12.4501
0.0002 289.366 +- 17.1531
0.0001 409.098 +- 24.901
