# generated by running 
# ./area-border-fractal-dimension -cam -ghost_area $a 
# with many ghost areas
# format: area (requested, not actual...) av.jet.border-length error
0.2 4.72464 +- 0.225112
0.1 8.33333 +- 0.352598
0.05 15.4861 +- 0.439623
0.025 23.8904 +- 0.582129
0.0125 38.4267 +- 0.9607
0.00625 59.36 +- 1.47662
0.003125 91.4189 +- 2.18524
0.0015 143.194 +- 3.04521
0.00075 214.466 +- 4.88849
0.000375 310.782 +- 6.08642
0.0002 461.93 +- 10.1038
0.0001 675.933 +- 15.0387
