# generated by running 
# ./area-border-fractal-dimension -kt -ghost_area $a 
# with many ghost areas
# format: area (requested, not actual...) av.jet.border-length error
0.2 4.78261 +- 0.209401
0.1 8.58824 +- 0.31653
0.05 14.8133 +- 0.392127
0.025 24.7714 +- 0.665373
0.0125 38.7051 +- 0.83706
0.00625 59.0769 +- 1.3341
0.003125 95.8286 +- 2.27125
0.0015 141.013 +- 3.25508
0.00075 212.613 +- 4.7181
0.000375 321.08 +- 6.10399
0.0002 487.536 +- 10.0873
0.0001 703.278 +- 15.4194
